### ISSUE TITLE
Python.h not find

### ISSUE THREAD

**Issue by JcmeLs** [joaoventura/pybridge#1]
Hi, joaoventura 
     When I want to embed Python in Android,I discover your blog--http://joaoventura.net/blog/2014/python-android/    .Thank for you share this bolg.It help me a lot.But,you use Eclipse to build it,I use android studio.I can build libpython.so.But when I want to run project,it can't find Python.h.I don't know how to fix it.Can you help me?

**Comment by joaoventura** [comment]
The PyBridge is a new approach that has nothing to do with those blog posts from 2014. Just ignore them, read the instructions on https://github.com/joaoventura/pybridge to setup and run the sample project. Do make sure you correctly set the path of the Crystax NDK.
You can open the PyBridge sample project from Android Studio.
