### ISSUE TITLE
Including library python

### ISSUE THREAD

**Issue by fedicherif** [joaoventura/pybridge#14]
Hey, how can i include numpy library in this project ?

**Comment by joaoventura** [comment]
Probably you'll have to cross-compile to android with the crystax-ndk. I'm leaving this issue open, maybe someone can help you!

**Comment by fedicherif** [comment]
thank you

**Comment by frmdstryr** [comment]
You can try using [conda-mobile](https://github.com/codelv/conda-mobile) for this.  I made it for [enaml-native](https://github.com/codelv/enaml-native) but it should work for any Android project targeting API >= 21.

It has python, numpy, and various other libraries and extensions compiled for android that you can install and use.  It's also fairly straightforward to add new "recipes" for other extensions with it.

**Comment by abelokon955** [comment]
@joaoventura How would cross-compiling look like? Let's say I would want to add the OpenCV2 Python library

**Comment by joaoventura** [comment]
This project now uses the python-for-android toolchain and they seem to have some recipes for compiling lots of python modules (https://github.com/kivy/python-for-android/tree/develop/pythonforandroid/recipes).
