### ISSUE TITLE
ImportError: No module named 'select'

### ISSUE THREAD

**Issue by kato-megumi** [joaoventura/pybridge#18]
I think the stdlib.zip is lacking some modules. Like select, _ctypes or _socket.
This is error log:

> File "/data/user/0/com.jventura.pyapp/assets/python/stdlib.zip/platform.py", line 115, in <module>
>       File "/data/user/0/com.jventura.pyapp/assets/python/stdlib.zip/subprocess.py", line 438, in <module>
>     ImportError: No module named 'select'

**Comment by kabukky** [comment]
Same problem here. Is there a way to get the full stdlib? I guess "select" requires additional native libraries to run?

**Comment by kabukky** [comment]
Fixed it by copying the `select.so` from the crystax-sdk. But now I'm getting:

```
ImportError: The 'appdirs' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
```

**Comment by kabukky** [comment]
I got it all working by tracking down every package that was missing. Works great now :)

**Comment by ZhangKuixun** [comment]
I have error.not found _ctypes in stdlib.zip

> Initializing the Python interpreter
> `--------------------`
> --PyRun_SimpleString("import bootstrap");
> pathpath=/data/data/com.jventura.pyapp/assets/python/bootstrap.py
> pathpath---/data/data/com.jventura.pyapp/assets
> Traceback (most recent call last):
> File "", line 1, in 
> File "/data/user/0/com.jventura.pyapp/assets/python/bootstrap.py", line 11, in 
> import youtube_dl
> File "/data/data/com.jventura.pyapp/assets/python/youtube_dl/init.py", line 15, in 
> from .options import (
> File "/data/data/com.jventura.pyapp/assets/python/youtube_dl/options.py", line 8, in 
> from .downloader.external import list_external_downloaders
> File "/data/data/com.jventura.pyapp/assets/python/youtube_dl/downloader/init.py", line 3, in 
> from .common import FileDownloader
> File "/data/data/com.jventura.pyapp/assets/python/youtube_dl/downloader/common.py", line 9, in 
> from ..compat import compat_os_name
> File "/data/data/com.jventura.pyapp/assets/python/youtube_dl/compat.py", line 7, in 
> import ctypes
> File "/data/user/0/com.jventura.pyapp/assets/python/stdlib.zip/ctypes/init.py", line 7, in
ImportError: No module named '_ctypes'
`--------------------`

File directory：
assets
--python
----youtube_dl
----bootstrap.py
----stdlib.zip

**Comment by ZhangKuixun** [comment]
@kato-megumi

**Comment by joaoventura** [comment]
@ZhangKuixun Issues are not meant to be (ab)used for user support like you've been doing so far, so please don't do this here! 👎
