### ISSUE TITLE
SIGSEGV

### ISSUE THREAD

**Issue by gmli** [joaoventura/pybridge#20]
Hi,

has anyone tested it recently ?

It used to send stderr to logcat correctly, permitting us to debug an app easily, but it's not the case anymore.
If there is a problem in my Python code (improper code, exception raised), now the call terminates with this error : 

I/pybridge: Initializing the Python interpreter
I/pybridge: Call into Python interpreter
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x4 in tid 9120 (.jventura.pyapp), pid 9120 (.jventura.pyapp)
Disconnected from the target VM, address: 'localhost:8601', transport: 'socket'

With no log of what went wrong.

I use Android Studio 3.1.4 (linux) and crystax-ndk-10.3.2 (but this version of crystax used to work).

Any idea ?

Regards.

**Comment by joaoventura** [comment]
I have an application in production which has not seen any problems, but it was compiled with a older version of the Android SDK.

**Comment by gmli** [comment]
This week-end I've tested with Android 3.1.2 on Ubuntu 18.04 and the problem is the same.

**Comment by joaoventura** [comment]
This project uses a Python library compiled for armv7, I don't know if it runs on the Android emulator..
