### ISSUE TITLE
How to install crystax-ndk in Mac?

### ISSUE THREAD

**Issue by ZhangKuixun** [joaoventura/pybridge#21]
Hello, How to install crystax-ndk in Mac? I not way to find it.

[https://brewinstall.org/install-crystax-ndk-on-mac-with-brew/](https://brewinstall.org/install-crystax-ndk-on-mac-with-brew/)

Homebrew Install success.
but execute `brew install crystax-ndk` error:
> zhangkuixun$ brew install crystax-ndk
> Error: No available formula with the name "crystax-ndk" 
> It was migrated from homebrew/core to homebrew/cask.
> You can access it again by running:
>   brew tap homebrew/cask
> And then you can install it by running:
>   brew cask install crystax-ndk

**Comment by JMSS-Unknown** [comment]
Did you try what the error message says?
Run `brew tap homebrew/cask` and then `brew cask install crystax-ndk`?

**Comment by ZhangKuixun** [comment]
Ok,Thanks

**Comment by joaoventura** [comment]
Issues are not meant to be (ab)used for user support like you've been doing so far, so please don't do this here! 👎
