### ISSUE TITLE
How to include python .so modules (e.g. select.so) for all architectures?

### ISSUE THREAD

**Issue by kabukky** [joaoventura/pybridge#22]
Hi,
is there a way to include the `$(CRYSTAX_PATH)/sources/python/3.5/libs/$(TARGET_ARCH_ABI)/modules/select.so` file for all architectures?

I know I can copy the `select.so` to the `assets/python` folder - that works. But that will only include it for one architecture.

I tried it like this, in the `Android.mk`, but the python interpreter can't find it:

```
# Include select.so

include $(CLEAR_VARS)
LOCAL_MODULE    := select
LOCAL_SRC_FILES := $(CRYSTAX_PATH)/sources/python/3.5/libs/$(TARGET_ARCH_ABI)/modules/select.so
include $(PREBUILT_SHARED_LIBRARY)
```

Error:

```
com.jventura.pyapp I/pybridge: ImportError: No module named 'select'
```

**Comment by kabukky** [comment]
Here's the workaround I'm using now:

In PyBridge.java:

```
    public static JSONObject call(JSONObject payload) {
        try {
            String[] abis = Build.SUPPORTED_ABIS;
            payload.put("architecture", abis[0]);
            String result = call(payload.toString());
            return new JSONObject(result);
        } catch (JSONException e) {
            e.printStackTrace();
            return null;
        }
    }
```

In bootrap.py:

```
 import os
 sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)) + '/libs/' + args['architecture'])
```

Then I put the .so files in the corresponding `assets/python/libs/<arch>` folders.

That works fine. Is there a better way?

**Comment by ZhangKuixun** [comment]
I have error.not found _ctypes in stdlib.zip

> Initializing the Python interpreter
> `--------------------`
> --PyRun_SimpleString("import bootstrap");
> pathpath=/data/data/com.jventura.pyapp/assets/python/bootstrap.py
> pathpath---/data/data/com.jventura.pyapp/assets
> Traceback (most recent call last):
> File "", line 1, in 
> File "/data/user/0/com.jventura.pyapp/assets/python/bootstrap.py", line 11, in 
> import youtube_dl
> File "/data/data/com.jventura.pyapp/assets/python/youtube_dl/init.py", line 15, in 
> from .options import (
> File "/data/data/com.jventura.pyapp/assets/python/youtube_dl/options.py", line 8, in 
> from .downloader.external import list_external_downloaders
> File "/data/data/com.jventura.pyapp/assets/python/youtube_dl/downloader/init.py", line 3, in 
> from .common import FileDownloader
> File "/data/data/com.jventura.pyapp/assets/python/youtube_dl/downloader/common.py", line 9, in 
> from ..compat import compat_os_name
> File "/data/data/com.jventura.pyapp/assets/python/youtube_dl/compat.py", line 7, in 
> import ctypes
> File "/data/user/0/com.jventura.pyapp/assets/python/stdlib.zip/ctypes/init.py", line 7, in
ImportError: No module named '_ctypes'
`--------------------`

File directory：
assets
--python
----youtube_dl
----bootstrap.py
----stdlib.zip
@kabukky

**Comment by ZhangKuixun** [comment]
I have the same problem. How did you solve it?

**Comment by ZhangKuixun** [comment]
I have the same problem. How did you solve it?

**Comment by ZhangKuixun** [comment]
I have the same problem. How did you solve it?

**Comment by kabukky** [comment]
@ZhangKuixun see my workaround above.

You should put 

```
 import os
 sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)) + '/libs/' + args['architecture'])
```

at the top of the python function you are calling since that is where you will have access to `args['architecture']`.

**Comment by ZhangKuixun** [comment]
Failure, there are still the same mistakes @kabukky

**Comment by ZhangKuixun** [comment]
Do you need to put it in platform.py and subprocess.py?

**Comment by ZhangKuixun** [comment]
>   File "/data/user/0/com.jventura.pyapp/assets/python/stdlib.zip/platform.py", line 115, in <module>
>   File "/data/user/0/com.jventura.pyapp/assets/python/stdlib.zip/subprocess.py", line 438, in <module>
> ImportError: No module named 'select'

`sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)) + '/libs/arm64-v8a')` in bootstrap.py

**Comment by ZhangKuixun** [comment]
_ctypes.so has been solved, I annotate it.

**Comment by ZhangKuixun** [comment]
this is my demo, https://github.com/ZhangKuixun/pybridge(https://github.com/ZhangKuixun/pybridge) Can you take a look at it for me? @kabukky

**Comment by joaoventura** [comment]
@ZhangKuixun, please don't open issues begging for user support like you have been doing..
