### ISSUE TITLE
APP_ABI := all

### ISSUE THREAD

**Issue by kabukky** [joaoventura/pybridge#23]
In the `Application.mk`, `APP_ABI` is set to `armeabi-v7a x86`.
Is there a reason for this? Maybe a limitation of the python interpreter?
I would like to set it to `APP_ABI := all`.

**Comment by joaoventura** [comment]
It is there as an example such that it works on a real device. You can set it to all architectures you want to support, but you must take care to copy all the necessary shared libraries for all architectures (which will imply a big apk file)..
