### ISSUE TITLE
ImportError: No module named 'select'

### ISSUE THREAD

**Issue by ZhangKuixun** [joaoventura/pybridge#25]
I have error, not found `select` in `stdlib.zip`

> Initializing the Python interpreter
> `--------------------`
> --PyRun_SimpleString("import bootstrap");
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/user/0/com.jventura.pyapp/assets/python/bootstrap.py", line 13, in <module>
    import platform
  File "/data/user/0/com.jventura.pyapp/assets/python/stdlib.zip/platform.py", line 115, in <module>
  File "/data/user/0/com.jventura.pyapp/assets/python/stdlib.zip/subprocess.py", line 438, in <module>
ImportError: No module named 'select'
`--------------------`

File directory：
assets
--python
----bootstrap.py
----stdlib.zip

@edenbd50

**Comment by ZhangKuixun** [comment]
@joaoventura   @kato-megumi

**Comment by ZhangKuixun** [comment]
already solve

**Comment by ZhangKuixun** [comment]
yes, I use this `crystax-ndk-10.3.2/sources/python/3.5/libs/armeabi-v7a/modules/_ctypes.so.`

my android.mk:
> LOCAL_PATH := $(call my-dir)
> CRYSTAX_PATH := /usr/local/Caskroom/crystax-ndk/10.3.2/crystax-ndk-10.3.2
> 
> # 运行：
> # cd app/src/main/jni
> # ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk
> 
> # Build libpybridge.so
> 
> include $(CLEAR_VARS)
> LOCAL_MODULE    := pybridge
> LOCAL_SRC_FILES := pybridge.c
> LOCAL_LDLIBS := -llog
> LOCAL_SHARED_LIBRARIES := python3.5m
> include $(BUILD_SHARED_LIBRARY)
> 
> 
> # Include libpython3.5m.so
> 
> include $(CLEAR_VARS)
> LOCAL_MODULE    := python3.5m
> LOCAL_SRC_FILES := $(CRYSTAX_PATH)/sources/python/3.5/libs/$(TARGET_ARCH_ABI)/libpython3.5m.so
> LOCAL_EXPORT_CFLAGS := -I $(CRYSTAX_PATH)/sources/python/3.5/include/python/
> include $(PREBUILT_SHARED_LIBRARY)
> 
> 
> # Include select.so
> 
> include $(CLEAR_VARS)
> LOCAL_MODULE    := select
> LOCAL_SRC_FILES := $(CRYSTAX_PATH)/sources/python/3.5/libs/$(TARGET_ARCH_ABI)/modules/select.so
> include $(PREBUILT_SHARED_LIBRARY)
> 
> # Include select.so
> 
> include $(CLEAR_VARS)
> LOCAL_MODULE    := _ctypes
> LOCAL_SRC_FILES := $(CRYSTAX_PATH)/sources/python/3.5/libs/$(TARGET_ARCH_ABI)/modules/_ctypes.so
> include $(PREBUILT_SHARED_LIBRARY)

than use `sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)) + '/libs/arm64-v8a/select.so')` write in `bootstrap.py`

file dir:

> assets
> --python
> ----youtube_dl
> ----__init__.py
> ----bootstrap.py
> ----stdlib.zip
>----test.py

**Comment by ZhangKuixun** [comment]
> Have you tried putting the `_ctypes.so` file from the crystax-ndk into `assets/python`? You need to use the right one for your architecture, e.g. `crystax-ndk-10.3.2/sources/python/3.5/libs/armeabi-v7a/modules/_ctypes.so`.

I tried  putting the `_ctypes.so` file from the crystax-ndk into `assets/python` . can solve.

**Comment by ZhangKuixun** [comment]
@kabukky 
have a new question, never found _ssl.so in my computer and net.
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/data/user/0/com.jventura.pyapp/assets/python/bootstrap.py", line 9, in <module>
>     import ssl
>   File "/data/user/0/com.jventura.pyapp/assets/python/stdlib.zip/ssl.py", line 98, in <module>
> ImportError: No module named '_ssl'

**Comment by joaoventura** [comment]
Issues are not meant to be used for user support, please don't do this here! 👎

**Comment by ZhangKuixun** [comment]
> Issues are not meant to be used for user support, please don't do this here! 👎

sorry
