### ISSUE TITLE
No module named '_ssl'

### ISSUE THREAD

**Issue by ZhangKuixun** [joaoventura/pybridge#26]
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/data/user/0/com.jventura.pyapp/assets/python/bootstrap.py", line 9, in <module>
>     import ssl
>   File "/data/user/0/com.jventura.pyapp/assets/python/stdlib.zip/ssl.py", line 98, in <module>
> ImportError: No module named '_ssl'

**Comment by joaoventura** [comment]
Issues are not meant to be used for user support, please don't do this here! 👎
