### ISSUE TITLE
Question: How to import module based on c libraries

### ISSUE THREAD

**Issue by OleksandrGrument** [joaoventura/pybridge#28]
Hello, i'm trying to add the module PIL that based on c libraries:
Here i found the download link with the pil module and c classes for python 3
https://archlinuxarm.org/packages/aarch64/python-pillow

I'm adding them to the project and all time i'm getting error like 
No module named '_imaging'  - Imaging.h is c file 

But the c files is already in assets, how to properly configure it. Thanks for any help.

**Comment by t0june** [comment]
did you solve this problem?

**Comment by joaoventura** [comment]
C files must be compiled first.. This project now uses the python-for-android toolchain and they seem to have some recipes for compiling Pillow..
