### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by frmdstryr** [joaoventura/pybridge#6]
In https://github.com/joaoventura/pybridge#running-the-project

You should change "Finally, open the terminal and run path/to/crystax/ndk-build" to "Finally, open the terminal, cd to app/src/main/jni, and run path/to/crystax/ndk-build"

Otherwise you get the error:
```
Android NDK: Could not find application project directory !    
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.    
/home/jrm/Android/Crystax/crystax-ndk-10.3.2/build/core/build-local.mk:143: *** Android NDK: Aborting    .  Stop.
```

Thanks!

**Comment by joaoventura** [comment]
Thanks for the suggestion! 👍

**Comment by ZhangKuixun** [comment]
How to solve this problem?
