### ISSUE TITLE
How to install crystax NDK in linux ?

### ISSUE THREAD

**Issue by mayur19** [joaoventura/pybridge#7]
Hi , 
can please explain me briefly how to install crystax NDK in linux ?

**Comment by joaoventura** [comment]
I'm not completely sure that Github issues is the right place to ask for third-party lib support but anyway, here's your answer: there's no installation, just unzip/untar it somewhere on your local filesystem..

**Comment by mayur19** [comment]
Okay thank you . Can i able to integrate my own python programs using this ?
